\set ON_ERROR_STOP
\set ECHO all
BEGIN;
\set ECHO all
CREATE SEQUENCE "public"."areas_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."areas"."id";
CREATE SEQUENCE "public"."aspnetroleclaims_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."aspnetroleclaims"."id";
CREATE SEQUENCE "public"."aspnetuserclaims_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."aspnetuserclaims"."id";
CREATE SEQUENCE "public"."reservations_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."reservations"."id";
CREATE SEQUENCE "public"."reservationstatuses_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."reservationstatuses"."id";
CREATE SEQUENCE "public"."reservationtypes_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."reservationtypes"."id";
CREATE SEQUENCE "public"."restaurants_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."restaurants"."id";
CREATE SEQUENCE "public"."sittings_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."sittings"."id";
CREATE SEQUENCE "public"."sittingstatuses_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."sittingstatuses"."id";
CREATE SEQUENCE "public"."sittingtypes_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."sittingtypes"."id";
CREATE SEQUENCE "public"."tablereservations_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."tablereservations"."id";
CREATE SEQUENCE "public"."tables_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."tables"."id";
CREATE SEQUENCE "public"."tablesittings_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."tablesittings"."id";
CREATE SEQUENCE "public"."user_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "public"."user"."id";
ALTER TABLE "public"."areas" ADD CONSTRAINT "pk_areas" PRIMARY KEY ("id");
ALTER TABLE "public"."aspnetroleclaims" ADD CONSTRAINT "pk_aspnetroleclaims" PRIMARY KEY ("id");
ALTER TABLE "public"."aspnetroles" ADD CONSTRAINT "pk_aspnetroles" PRIMARY KEY ("id");
ALTER TABLE "public"."aspnetuserclaims" ADD CONSTRAINT "pk_aspnetuserclaims" PRIMARY KEY ("id");
ALTER TABLE "public"."aspnetuserlogins" ADD CONSTRAINT "pk_aspnetuserlogins" PRIMARY KEY ("loginprovider","providerkey");
ALTER TABLE "public"."aspnetuserroles" ADD CONSTRAINT "pk_aspnetuserroles" PRIMARY KEY ("userid","roleid");
ALTER TABLE "public"."aspnetusertokens" ADD CONSTRAINT "pk_aspnetusertokens" PRIMARY KEY ("userid","loginprovider","name");
ALTER TABLE "public"."aspnetusers" ADD CONSTRAINT "pk_aspnetusers" PRIMARY KEY ("id");
ALTER TABLE "public"."people" ADD CONSTRAINT "pk_people" PRIMARY KEY ("id");
ALTER TABLE "public"."reservationstatuses" ADD CONSTRAINT "pk_reservationstatuses" PRIMARY KEY ("id");
ALTER TABLE "public"."reservationtypes" ADD CONSTRAINT "pk_reservationtypes" PRIMARY KEY ("id");
ALTER TABLE "public"."reservations" ADD CONSTRAINT "pk_reservations" PRIMARY KEY ("id");
ALTER TABLE "public"."restaurants" ADD CONSTRAINT "pk_restaurants" PRIMARY KEY ("id");
ALTER TABLE "public"."sittingstatuses" ADD CONSTRAINT "pk_sittingstatuses" PRIMARY KEY ("id");
ALTER TABLE "public"."sittingtypes" ADD CONSTRAINT "pk_sittingtypes" PRIMARY KEY ("id");
ALTER TABLE "public"."sittings" ADD CONSTRAINT "pk_sittings" PRIMARY KEY ("id");
ALTER TABLE "public"."tablereservations" ADD CONSTRAINT "pk_tablereservations" PRIMARY KEY ("id");
ALTER TABLE "public"."tablesittings" ADD CONSTRAINT "pk_tablesittings" PRIMARY KEY ("id");
ALTER TABLE "public"."tables" ADD CONSTRAINT "pk_tables" PRIMARY KEY ("id");
ALTER TABLE "public"."user" ADD CONSTRAINT "pk_user" PRIMARY KEY ("id");
ALTER TABLE "public"."__efmigrationshistory" ADD CONSTRAINT "pk___efmigrationshistory" PRIMARY KEY ("migrationid");
ALTER TABLE "public"."areas" ADD CONSTRAINT "fk_areas_restaurants_restaurantid" FOREIGN KEY ("restaurantid") REFERENCES "public"."restaurants" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."aspnetroleclaims" ADD CONSTRAINT "fk_aspnetroleclaims_aspnetroles_roleid" FOREIGN KEY ("roleid") REFERENCES "public"."aspnetroles" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."aspnetuserclaims" ADD CONSTRAINT "fk_aspnetuserclaims_aspnetusers_userid" FOREIGN KEY ("userid") REFERENCES "public"."aspnetusers" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."aspnetuserlogins" ADD CONSTRAINT "fk_aspnetuserlogins_aspnetusers_userid" FOREIGN KEY ("userid") REFERENCES "public"."aspnetusers" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."aspnetuserroles" ADD CONSTRAINT "fk_aspnetuserroles_aspnetroles_roleid" FOREIGN KEY ("roleid") REFERENCES "public"."aspnetroles" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."aspnetuserroles" ADD CONSTRAINT "fk_aspnetuserroles_aspnetusers_userid" FOREIGN KEY ("userid") REFERENCES "public"."aspnetusers" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."aspnetusertokens" ADD CONSTRAINT "fk_aspnetusertokens_aspnetusers_userid" FOREIGN KEY ("userid") REFERENCES "public"."aspnetusers" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."people" ADD CONSTRAINT "fk_people_people_staff_managerid" FOREIGN KEY ("staff_managerid") REFERENCES "public"."people" ( "id");
ALTER TABLE "public"."people" ADD CONSTRAINT "fk_people_restaurants_restaurantid" FOREIGN KEY ("restaurantid") REFERENCES "public"."restaurants" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."reservations" ADD CONSTRAINT "fk_reservations_people_customerid" FOREIGN KEY ("customerid") REFERENCES "public"."people" ( "id");
ALTER TABLE "public"."reservations" ADD CONSTRAINT "fk_reservations_reservationstatuses_reservationstatusid" FOREIGN KEY ("reservationstatusid") REFERENCES "public"."reservationstatuses" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."reservations" ADD CONSTRAINT "fk_reservations_reservationtypes_reservationtypeid" FOREIGN KEY ("reservationtypeid") REFERENCES "public"."reservationtypes" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."reservations" ADD CONSTRAINT "fk_reservations_user_userid" FOREIGN KEY ("userid") REFERENCES "public"."user" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."sittings" ADD CONSTRAINT "fk_sittings_sittingstatuses_sittingstatusid" FOREIGN KEY ("sittingstatusid") REFERENCES "public"."sittingstatuses" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."sittings" ADD CONSTRAINT "fk_sittings_sittingtypes_sittingtypeid" FOREIGN KEY ("sittingtypeid") REFERENCES "public"."sittingtypes" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."tablereservations" ADD CONSTRAINT "fk_tablereservations_reservations_reservationid" FOREIGN KEY ("reservationid") REFERENCES "public"."reservations" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."tablereservations" ADD CONSTRAINT "fk_tablereservations_tablesittings_tablesittingid" FOREIGN KEY ("tablesittingid") REFERENCES "public"."tablesittings" ( "id");
ALTER TABLE "public"."tablesittings" ADD CONSTRAINT "fk_tablesittings_sittings_sittingid" FOREIGN KEY ("sittingid") REFERENCES "public"."sittings" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."tablesittings" ADD CONSTRAINT "fk_tablesittings_tables_tableid" FOREIGN KEY ("tableid") REFERENCES "public"."tables" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."tables" ADD CONSTRAINT "fk_tables_areas_areaid" FOREIGN KEY ("areaid") REFERENCES "public"."areas" ( "id") ON DELETE CASCADE;
ALTER TABLE "public"."user" ADD CONSTRAINT "fk_user_people_managerid" FOREIGN KEY ("managerid") REFERENCES "public"."people" ( "id");
ALTER TABLE "public"."user" ADD CONSTRAINT "fk_user_people_memberid" FOREIGN KEY ("memberid") REFERENCES "public"."people" ( "id");
ALTER TABLE "public"."user" ADD CONSTRAINT "fk_user_people_staffid" FOREIGN KEY ("staffid") REFERENCES "public"."people" ( "id");
ALTER TABLE "public"."areas" ALTER COLUMN "id" SET DEFAULT nextval('"public"."areas_id_seq"');
ALTER TABLE "public"."aspnetroleclaims" ALTER COLUMN "id" SET DEFAULT nextval('"public"."aspnetroleclaims_id_seq"');
ALTER TABLE "public"."aspnetuserclaims" ALTER COLUMN "id" SET DEFAULT nextval('"public"."aspnetuserclaims_id_seq"');
ALTER TABLE "public"."reservationstatuses" ALTER COLUMN "id" SET DEFAULT nextval('"public"."reservationstatuses_id_seq"');
ALTER TABLE "public"."reservationtypes" ALTER COLUMN "id" SET DEFAULT nextval('"public"."reservationtypes_id_seq"');
ALTER TABLE "public"."reservations" ALTER COLUMN "id" SET DEFAULT nextval('"public"."reservations_id_seq"');
ALTER TABLE "public"."restaurants" ALTER COLUMN "id" SET DEFAULT nextval('"public"."restaurants_id_seq"');
ALTER TABLE "public"."sittingstatuses" ALTER COLUMN "id" SET DEFAULT nextval('"public"."sittingstatuses_id_seq"');
ALTER TABLE "public"."sittingtypes" ALTER COLUMN "id" SET DEFAULT nextval('"public"."sittingtypes_id_seq"');
ALTER TABLE "public"."sittings" ALTER COLUMN "id" SET DEFAULT nextval('"public"."sittings_id_seq"');
ALTER TABLE "public"."tablereservations" ALTER COLUMN "id" SET DEFAULT nextval('"public"."tablereservations_id_seq"');
ALTER TABLE "public"."tablesittings" ALTER COLUMN "id" SET DEFAULT nextval('"public"."tablesittings_id_seq"');
ALTER TABLE "public"."tables" ALTER COLUMN "id" SET DEFAULT nextval('"public"."tables_id_seq"');
ALTER TABLE "public"."user" ALTER COLUMN "id" SET DEFAULT nextval('"public"."user_id_seq"');
select setval('"public"."areas_id_seq"',(select max("id") from "public"."areas")::bigint);
select setval('"public"."aspnetroleclaims_id_seq"',(select max("id") from "public"."aspnetroleclaims")::bigint);
select setval('"public"."aspnetuserclaims_id_seq"',(select max("id") from "public"."aspnetuserclaims")::bigint);
select setval('"public"."reservations_id_seq"',(select max("id") from "public"."reservations")::bigint);
select setval('"public"."reservationstatuses_id_seq"',(select max("id") from "public"."reservationstatuses")::bigint);
select setval('"public"."reservationtypes_id_seq"',(select max("id") from "public"."reservationtypes")::bigint);
select setval('"public"."restaurants_id_seq"',(select max("id") from "public"."restaurants")::bigint);
select setval('"public"."sittings_id_seq"',(select max("id") from "public"."sittings")::bigint);
select setval('"public"."sittingstatuses_id_seq"',(select max("id") from "public"."sittingstatuses")::bigint);
select setval('"public"."sittingtypes_id_seq"',(select max("id") from "public"."sittingtypes")::bigint);
select setval('"public"."tablereservations_id_seq"',(select max("id") from "public"."tablereservations")::bigint);
select setval('"public"."tables_id_seq"',(select max("id") from "public"."tables")::bigint);
select setval('"public"."tablesittings_id_seq"',(select max("id") from "public"."tablesittings")::bigint);
select setval('"public"."user_id_seq"',(select max("id") from "public"."user")::bigint);
COMMIT;
